### ISSUE TITLE
Treffen mit Korrektor

### ISSUE THREAD

**Issue by pabay101** [ProPra16/programmierpraktikum-abschlussprojekt-die3lustigen4-2#1]
Hallo zusammen,

ich würde mich gerne einmal für 5-10 Minuten mit euch treffen, um sicherzustellen, dass alles gut läuft. Im Protokoll habe ich gelesen, dass ihr euch am Dienstag um 16 Uhr treffen wollt, wenn ihr das an der Uni vorhabt, könnte ich zB dann kurz vorbeikommen.

LG,
Euer Korrektor Paul

**Comment by BlackCritical** [comment]
Ja, wir wollten uns in der Uni treffen also sollte das kein Problem sein. Wahrscheinlich in einem der Räume in der Bibliothek im Gebäude 25.

**Comment by sihab101** [comment]
Jo Leute, wir treffen uns um 16 Uhr vor dem Hörsaal 5G.
Korrektor Paul - es wäre nett wenn du kurz zusagen bzw. einen alternatien Termin vorschlagen würdest.
Falls du später kommen möchtest werden wir unseren endgültigen Standort hier nochmal rein schreiben, sonst bitte anrufen: 0160 90796329
Gruß

**Comment by KorrektorPaul** [comment]
Alles klar. Ich kann pünktlich kommen, oder erst später, wie es euch lieber ist. Wenn ich von euch nichts mehr höre, bin ich dann auch um 16 Uhr vor 5G

**Comment by sihab101** [comment]
In Ordnung, 16 Uhr dann, bis später! ;)
